language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
    - sshpass
install:
  - yarn
script:
  - export PROD_TOKEN=$TOKEN
  - npm run build
after_success:
  - export SSHPASS=$VPS_PWD
  - sshpass -e ssh -o stricthostkeychecking=no root@139.199.22.90 "sh /data/wwwroot/coc.yunyoujun.cn/deploy-ci.sh {$TOKEN}"